name: Test
on: [push, pull_request]


jobs:
  test:
    name: Test go package with go version ${{ matrix.go_version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go_version: [1.19.x, 1.20.x, 1.21.x]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with: 
          redis-version: 6

      - name: Install redis cli # so we can test the server
        run: sudo apt-get install -y redis-tools

      - name: Verify that redis is up
        run: redis-cli ping

      - name: Setup go
        uses: actions/setup-go@v3
        with: 
          go-version: ${{ matrix.go_version }}

      - name: Testing code
        run: go test -race -cover ./...